In [ ]:
import pandas as pd
from io import StringIO
from urllib.parse import urlparse

import re
import emoji
import gc

In [ ]:
bad_lines = []

def bad_line_handler(line):
    bad_lines.append(line)
    return None  # Zeile überspringen

chunks = pd.read_csv(
    "bitcoin-tweets-2021.csv",
    chunksize=100_000,
    engine="python",          # 🔴 extrem wichtig
    on_bad_lines=bad_line_handler
)

In [ ]:
print(f"Anzahl bad lines: {len(bad_lines)}")

Anzahl bad lines: 0

In [ ]:
df_raw = pd.concat(chunks)

In [ ]:
del chunks
del bad_lines
gc.collect()

30

In [ ]:
df_raw.columns

Index(['datetime', 'username', 'text'], dtype='object')

In [ ]:
len(df_raw)

15630696

In [ ]:
wrong_text_rows = df_raw[~df_raw["text"].apply(lambda x: isinstance(x, str))]

In [ ]:
wrong_text_rows

                                                   datetime username  text
891075                              https://t.co/u3iraDb6VV     None  None
891076                                         #ITintheD383     None  None
1134125                             https://t.co/fRl6ZV3d8Z     None  None
1134126                                        #ITintheD384     None  None
1416485               #FelizTarde 👉 https://t.co/i9zJ57T14Y     None  None
...                                                     ...      ...   ...
14939818    #trading #emprende #FelizSabado 👉 https://t....     None  None
15483967                                 hot bitcoin roomba     None  None
15483968                         tremble traffic expressly      None  None
15483969            the buggy brickwork grows this concrete     None  None
15498468                            https://t.co/8BmAq56SGy     None  None

[387 rows x 3 columns]

In [ ]:
wrong_text_ids = wrong_text_rows.index.tolist()
print("Zeilen mit falschem Typ:", wrong_text_ids)

Zeilen mit falschem Typ: [891075, 891076, 1134125, 1134126, 1416485, 3296300, 3296301, 3296302, 3296303, 3296304, 3296305, 3296306, 3296307, 3296308, 3296309, 3296310, 3296311, 3407877, 3407878, 3407879, 3407880, 3407881, 3407882, 3407883, 3407884, 3407885, 3407886, 3407887, 3407888, 3410683, 3410684, 3410685, 3410686, 3410687, 3410688, 3410689, 3410690, 3410691, 3410692, 3410693, 3410694, 3646111, 3646112, 3884318, 4102517, 4831633, 4831634, 5067033, 5067034, 5067035, 5067036, 5067037, 5181241, 5462725, 5800894, 5831097, 6039323, 6039324, 6673666, 6674412, 6676961, 6716830, 6752594, 6755338, 6828536, 6847565, 7057852, 7324540, 7398073, 7424834, 7556694, 7556695, 7685607, 7686349, 7768062, 8111045, 8111046, 8111047, 8126279, 8126280, 8126281, 8612561, 8830967, 8907561, 8925904, 8965799, 9283449, 9283450, 9283451, 9283452, 9506944, 9562014, 9684018, 9726205, 9857644, 9902884, 9916874, 9916875, 9917167, 9917168, 9973498, 9976697, 10132626, 10150111, 10150112, 10199673, 10219080, 10219081, 10267609, 10277040, 10277041, 10283988, 10283989, 10321546, 10428223, 10429412, 10479138, 10533241, 10549069, 10549070, 10630133, 10700835, 11305218, 11641360, 11734041, 11924427, 11924515, 11947740, 11947741, 11947742, 11947743, 12094322, 12131017, 12255705, 12428937, 12429491, 12429492, 12431054, 12431218, 12432141, 12464650, 12476943, 12476944, 12476945, 12476946, 12476947, 12476948, 12476949, 12506498, 12508213, 12508711, 12508712, 12508713, 12508714, 12508818, 12509081, 12509845, 12509846, 12509847, 12520349, 12520350, 12520351, 12520492, 12535426, 12535427, 12539591, 12539592, 12539593, 12539594, 12551982, 12569630, 12569631, 12569929, 12569930, 12569982, 12569983, 12569984, 12569985, 12570044, 12570101, 12570102, 12570103, 12570349, 12570486, 12570487, 12570488, 12570489, 12570689, 12571592, 12579011, 12579117, 12579216, 12579291, 12579292, 12579293, 12579319, 12579320, 12579469, 12579571, 12579635, 12579669, 12579715, 12579741, 12579772, 12580060, 12605208, 12605209, 12610848, 12621107, 12621108, 12621220, 12621418, 12621419, 12621420, 12621988, 12621989, 12622964, 12622965, 12622966, 12623087, 12623088, 12623089, 12623580, 12623581, 12624195, 12624196, 12625653, 12628217, 12628218, 12629747, 12629748, 12637152, 12637153, 12638821, 12638822, 12639073, 12639074, 12639274, 12639275, 12639590, 12639591, 12639873, 12639874, 12639875, 12639876, 12640006, 12651672, 12656421, 12661159, 12661342, 12666311, 12666312, 12688897, 12688898, 12688899, 12689656, 12691533, 12691534, 12691725, 12692999, 12694133, 12694134, 12694135, 12704071, 12704072, 12704073, 12705171, 12705598, 12712027, 12713926, 12713927, 12713972, 12713973, 12714149, 12714787, 12714788, 12725408, 12725409, 12725609, 12725610, 12725692, 12725693, 12739820, 12739821, 12756377, 12756434, 12756522, 12756523, 12756524, 12757154, 12757155, 12757402, 12757403, 12757404, 12757561, 12757562, 12757818, 12758888, 12768163, 12768772, 12769259, 12769358, 12769803, 12769804, 12770595, 12770596, 12780036, 12780037, 12780691, 12780729, 12781536, 12781922, 12782612, 12782613, 12790216, 12790217, 12790218, 12790221, 12790222, 12790223, 12812520, 12812676, 12812738, 12812820, 12812821, 12814660, 12815055, 12815056, 12815844, 12815845, 12815846, 12822915, 12822937, 12822938, 12822939, 12823106, 12861547, 12879969, 12879970, 12880371, 12880685, 12880686, 12880687, 12880730, 12880731, 12880732, 12880858, 12880859, 12880860, 12901329, 12901330, 12904951, 12904952, 12904999, 12905000, 12928099, 12928100, 12929667, 12929942, 12929943, 12968963, 12973520, 12991773, 13073051, 13074811, 13075041, 13075636, 13136812, 13954943, 13954944, 13954945, 13969935, 13969936, 13984240, 14033597, 14161711, 14733924, 14741321, 14742576, 14743758, 14760031, 14767114, 14939818, 15483967, 15483968, 15483969, 15498468]

In [ ]:
df_raw["text"].apply(type).value_counts()

text
<class 'str'>         15630309
<class 'NoneType'>         387
Name: count, dtype: int64

In [ ]:
wrong_username_rows = df_raw[~df_raw["username"].apply(lambda x: isinstance(x, str))]

In [ ]:
wrong_username_rows

                                                   datetime username  text
891075                              https://t.co/u3iraDb6VV     None  None
891076                                         #ITintheD383     None  None
1134125                             https://t.co/fRl6ZV3d8Z     None  None
1134126                                        #ITintheD384     None  None
1416485               #FelizTarde 👉 https://t.co/i9zJ57T14Y     None  None
...                                                     ...      ...   ...
14939818    #trading #emprende #FelizSabado 👉 https://t....     None  None
15483967                                 hot bitcoin roomba     None  None
15483968                         tremble traffic expressly      None  None
15483969            the buggy brickwork grows this concrete     None  None
15498468                            https://t.co/8BmAq56SGy     None  None

[388 rows x 3 columns]

In [ ]:
wrong_username_ids = wrong_username_rows.index.tolist()
print("Zeilen mit falschem Typ:", wrong_username_ids)

Zeilen mit falschem Typ: [891075, 891076, 1134125, 1134126, 1416485, 3296300, 3296301, 3296302, 3296303, 3296304, 3296305, 3296306, 3296307, 3296308, 3296309, 3296310, 3296311, 3407877, 3407878, 3407879, 3407880, 3407881, 3407882, 3407883, 3407884, 3407885, 3407886, 3407887, 3407888, 3410683, 3410684, 3410685, 3410686, 3410687, 3410688, 3410689, 3410690, 3410691, 3410692, 3410693, 3410694, 3646111, 3646112, 3884318, 4102517, 4831633, 4831634, 5067033, 5067034, 5067035, 5067036, 5067037, 5181241, 5462725, 5567986, 5800894, 5831097, 6039323, 6039324, 6673666, 6674412, 6676961, 6716830, 6752594, 6755338, 6828536, 6847565, 7057852, 7324540, 7398073, 7424834, 7556694, 7556695, 7685607, 7686349, 7768062, 8111045, 8111046, 8111047, 8126279, 8126280, 8126281, 8612561, 8830967, 8907561, 8925904, 8965799, 9283449, 9283450, 9283451, 9283452, 9506944, 9562014, 9684018, 9726205, 9857644, 9902884, 9916874, 9916875, 9917167, 9917168, 9973498, 9976697, 10132626, 10150111, 10150112, 10199673, 10219080, 10219081, 10267609, 10277040, 10277041, 10283988, 10283989, 10321546, 10428223, 10429412, 10479138, 10533241, 10549069, 10549070, 10630133, 10700835, 11305218, 11641360, 11734041, 11924427, 11924515, 11947740, 11947741, 11947742, 11947743, 12094322, 12131017, 12255705, 12428937, 12429491, 12429492, 12431054, 12431218, 12432141, 12464650, 12476943, 12476944, 12476945, 12476946, 12476947, 12476948, 12476949, 12506498, 12508213, 12508711, 12508712, 12508713, 12508714, 12508818, 12509081, 12509845, 12509846, 12509847, 12520349, 12520350, 12520351, 12520492, 12535426, 12535427, 12539591, 12539592, 12539593, 12539594, 12551982, 12569630, 12569631, 12569929, 12569930, 12569982, 12569983, 12569984, 12569985, 12570044, 12570101, 12570102, 12570103, 12570349, 12570486, 12570487, 12570488, 12570489, 12570689, 12571592, 12579011, 12579117, 12579216, 12579291, 12579292, 12579293, 12579319, 12579320, 12579469, 12579571, 12579635, 12579669, 12579715, 12579741, 12579772, 12580060, 12605208, 12605209, 12610848, 12621107, 12621108, 12621220, 12621418, 12621419, 12621420, 12621988, 12621989, 12622964, 12622965, 12622966, 12623087, 12623088, 12623089, 12623580, 12623581, 12624195, 12624196, 12625653, 12628217, 12628218, 12629747, 12629748, 12637152, 12637153, 12638821, 12638822, 12639073, 12639074, 12639274, 12639275, 12639590, 12639591, 12639873, 12639874, 12639875, 12639876, 12640006, 12651672, 12656421, 12661159, 12661342, 12666311, 12666312, 12688897, 12688898, 12688899, 12689656, 12691533, 12691534, 12691725, 12692999, 12694133, 12694134, 12694135, 12704071, 12704072, 12704073, 12705171, 12705598, 12712027, 12713926, 12713927, 12713972, 12713973, 12714149, 12714787, 12714788, 12725408, 12725409, 12725609, 12725610, 12725692, 12725693, 12739820, 12739821, 12756377, 12756434, 12756522, 12756523, 12756524, 12757154, 12757155, 12757402, 12757403, 12757404, 12757561, 12757562, 12757818, 12758888, 12768163, 12768772, 12769259, 12769358, 12769803, 12769804, 12770595, 12770596, 12780036, 12780037, 12780691, 12780729, 12781536, 12781922, 12782612, 12782613, 12790216, 12790217, 12790218, 12790221, 12790222, 12790223, 12812520, 12812676, 12812738, 12812820, 12812821, 12814660, 12815055, 12815056, 12815844, 12815845, 12815846, 12822915, 12822937, 12822938, 12822939, 12823106, 12861547, 12879969, 12879970, 12880371, 12880685, 12880686, 12880687, 12880730, 12880731, 12880732, 12880858, 12880859, 12880860, 12901329, 12901330, 12904951, 12904952, 12904999, 12905000, 12928099, 12928100, 12929667, 12929942, 12929943, 12968963, 12973520, 12991773, 13073051, 13074811, 13075041, 13075636, 13136812, 13954943, 13954944, 13954945, 13969935, 13969936, 13984240, 14033597, 14161711, 14733924, 14741321, 14742576, 14743758, 14760031, 14767114, 14939818, 15483967, 15483968, 15483969, 15498468]

In [ ]:
df_raw["username"].apply(type).value_counts()

username
<class 'str'>         15630308
<class 'NoneType'>         387
<class 'float'>              1
Name: count, dtype: int64

In [ ]:
df_raw["datetime"].apply(type).value_counts()

datetime
<class 'str'>    15630696
Name: count, dtype: int64

In [ ]:
all_errors = list(set(wrong_text_ids + wrong_username_ids))

In [ ]:
df_raw = df_raw.drop(index=all_errors)

In [ ]:
df_raw.head(100)

,datetime,username,text
0,2021-01-01 23:59:58+00:00,WoodooProd,Crypto adoption in 2021: Top trends and predic...
1,2021-01-01 23:59:53+00:00,YSojourners,Ripple Executive Says US Laws on Crypto Are Va...
2,2021-01-01 23:59:53+00:00,Andama_n,@hextoysofficial | https://t.co/C6LPpuq05n Are...
3,2021-01-01 23:59:51+00:00,YSojourners,FUN and Games: Altcoin Drastically Pumps And D...
4,2021-01-01 23:59:50+00:00,HunnerSa,I bought #Bitcoin at 6k-8k-9k-12k-16k-19k and ...
...,...,...,...
95,2021-01-01 23:54:04+00:00,Cryptic_Oz,@CryptoCobain Use to love this coin when I was...
96,2021-01-01 23:54:02+00:00,FD_SignsOfWar,Checkout the latest #PatriotPowerHour (Episode...
97,2021-01-01 23:53:55+00:00,ConstructnRates,@CryptoTwittter @coin_artist I follow Immutabl...
98,2021-01-01 23:53:50+00:00,camendes,Michael Saylor vs. Keith McCullough | #Bitcoin...
99,2021-01-01 23:53:50+00:00,jbensnyder,@jessedo @Frances_Coppola @TheBlueMatt @alain_...

In [ ]:
df_raw= df_raw.sort_values(by="username")

In [ ]:
del all_errors
del wrong_username_ids
del wrong_username_rows
del wrong_text_ids
del wrong_text_rows
gc.collect()

0

In [ ]:
df_raw.to_csv("bitcoin_tweets.csv")

In [ ]:
del df_raw
gc.collect()

0

In [ ]:
chunks = pd.read_csv(
    "bitcoin_tweets.csv",
    chunksize=100_000,
    engine="python",
)

In [ ]:
df_raw = pd.concat(chunks)

In [ ]:
for i, text in enumerate(df_raw["text"]):
  if emoji.emoji_count(text) > 0:
    print(i, df_raw.iloc[i])
    break

4 Unnamed: 0                                             11343039
datetime                              2021-09-21 15:50:13+00:00
username                                           000000000OOK
text          This is not freedom. Bitcoin vision crumbling ...
Name: 4, dtype: object

In [ ]:
cutoff_date = pd.Timestamp('2021-10-19', tz= 'UTC')

In [ ]:
df_raw["datetime"] = pd.to_datetime(df_raw["datetime"])
mask = (df_raw['datetime'] <= cutoff_date)
df_raw = df_raw.loc[mask]

In [ ]:
del chunks
gc.collect()

30

In [ ]:
# Struktur
df_raw["hashtag_count"] = df_raw["text"].str.count(r"#\w+|HASHTAG_")
df_raw["url_count"] = df_raw["text"].str.count(r"URL_")
df_raw["mention_count"] = df_raw["text"].str.count(r"@\w+|MENTION")

# Typen
df_raw["is_retweet"] = df_raw["text"].str.lower().str.startswith("rt ").fillna(False).astype("int8")
df_raw["is_reply"] = df_raw["text"].str.match(r"@\w+").fillna(False).astype("int8")

# Stil
df_raw["tweet_len"] = df_raw["text"].str.len().fillna(False).astype("int16")
df_raw["has_caps"] = df_raw["text"].str.contains(r"\b[A-Z]{3,}\b").fillna(False).astype("int8")
df_raw["has_emoji"] = df_raw["text"].apply(lambda x: int(isinstance(x, str) and emoji.emoji_count(x) > 0)).astype("int8")
df_raw["emoji_count"] = df_raw["text"].apply(lambda x: emoji.emoji_count(x) if isinstance(x, str) else 0).astype("int16")
df_raw["has_exclamation"] = df_raw["text"].str.contains(r"!").fillna(False).astype("int8")

# Verhalten
df_raw["has_link"] = (df_raw["url_count"] > 0).fillna(False).astype("int8")

In [ ]:
user_meta = (
    df_raw
    .groupby("username", observed=True)
    .agg(
        tweet_count=("text", "size"),

        hashtags_per_tweet=("hashtag_count", "mean"),
        urls_per_tweet=("url_count", "mean"),
        mentions_per_tweet=("mention_count", "mean"),

        retweet_ratio=("is_retweet", "mean"),
        reply_ratio=("is_reply", "mean"),

        avg_tweet_len=("tweet_len", "mean"),
        caps_ratio=("has_caps", "mean"),
        emoji_ratio=("has_emoji", "mean"),
        emoji_count_ratio=("emoji_count", "mean"),
        exclamation_ratio=("has_exclamation", "mean"),

        link_tweet_ratio=("has_link", "mean"),
    )
    .reset_index()
)

In [ ]:
user_meta["no_link_tweet_ratio"] = 1.0 - user_meta["link_tweet_ratio"]
df_raw["datetime"] = pd.to_datetime(df_raw["datetime"])
df_raw["date"] = df_raw["datetime"].dt.date

tweets_per_day = (
    df_raw
    .groupby(["username", "date"])
    .size()
    .groupby("username")
    .mean()
)

user_meta["tweets_per_day"] = user_meta["username"].map(tweets_per_day)

In [ ]:
pattern = re.compile(r"@(\w+)")
counts = {}

for text in df_raw["text"]:
    if not isinstance(text, str):
        continue

    for mention in pattern.findall(text):
        counts[mention] = counts.get(mention, 0) + 1

In [ ]:
mentioned_count = (
    pd.DataFrame.from_dict(counts, orient="index", columns=["mentioned_by_others"])
      .rename_axis("username")
      .reset_index()
)

user_meta = user_meta.merge(
    mentioned_count,
    on="username",
    how="left"
)


user_meta["mentioned_by_others"] = user_meta["mentioned_by_others"].fillna(0)

In [ ]:
del pattern
del counts
del mentioned_count
gc.collect()

15

In [ ]:
user_meta.to_csv("meta_data_training.csv")

In [ ]:
user_meta.columns

Index(['username', 'tweet_count', 'hashtags_per_tweet', 'urls_per_tweet',
       'mentions_per_tweet', 'retweet_ratio', 'reply_ratio', 'avg_tweet_len',
       'caps_ratio', 'emoji_ratio', 'emoji_count_ratio', 'exclamation_ratio',
       'link_tweet_ratio', 'no_link_tweet_ratio', 'tweets_per_day',
       'mentioned_by_others'],
      dtype='object')

In [ ]:
user_meta.head(20)

,username,tweet_count,hashtags_per_tweet,urls_per_tweet,mentions_per_tweet,retweet_ratio,reply_ratio,avg_tweet_len,caps_ratio,emoji_ratio,emoji_count_ratio,exclamation_ratio,link_tweet_ratio,no_link_tweet_ratio,tweets_per_day,mentioned_by_others
0,0000000000KAIJU,1,1.000000,0.0,0.000000,0.0,0.000000,95.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.0,1.000000,0.0
1,000000000OOK,6,0.000000,0.0,0.833333,0.0,0.666667,145.500000,0.333333,0.166667,0.166667,0.000000,0.0,1.0,1.200000,3.0
2,00000000FF00,1,0.000000,0.0,1.000000,0.0,1.000000,75.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.0,1.000000,0.0
3,00000000jn,1,0.000000,0.0,1.000000,0.0,1.000000,22.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.0,1.000000,0.0
4,00000001_,1,0.000000,0.0,1.000000,0.0,0.000000,161.000000,1.000000,0.000000,0.000000,0.000000,0.0,1.0,1.000000,0.0
5,0000000dead,2,0.000000,0.0,2.000000,0.0,1.000000,262.500000,0.000000,0.000000,0.000000,0.500000,0.0,1.0,2.000000,0.0
6,00000786L,2,0.000000,0.0,1.500000,0.0,1.000000,58.500000,0.000000,0.500000,0.500000,0.500000,0.0,1.0,2.000000,0.0
7,0000078931463_k,1,0.000000,0.0,0.000000,0.0,0.000000,243.000000,1.000000,0.000000,0.000000,0.000000,0.0,1.0,1.000000,0.0
8,00000ab11,1,8.000000,0.0,1.000000,0.0,0.000000,235.000000,1.000000,0.000000,0.000000,0.000000,0.0,1.0,1.000000,0.0
9,00000nft,9,2.333333,0.0,0.777778,0.0,0.222222,128.111111,0.333333,0.666667,1.444444,0.333333,0.0,1.0,1.285714,0.0
10,00000scott,1,0.000000,0.0,2.000000,0.0,1.000000,93.000000,0.000000,1.000000,1.000000,0.000000,0.0,1.0,1.000000,0.0
11,0000AA127,1,0.000000,0.0,0.000000,0.0,0.000000,31.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.0,1.000000,0.0
12,0000FFCoin,1,0.000000,0.0,1.000000,0.0,1.000000,283.000000,1.000000,0.000000,0.000000,0.000000,0.0,1.0,1.000000,0.0
13,0000N1CK,1,0.000000,0.0,1.000000,0.0,1.000000,74.000000,0.000000,1.000000,1.000000,0.000000,0.0,1.0,1.000000,0.0
14,0000Yoyo,1,5.000000,0.0,2.000000,0.0,1.000000,250.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.0,1.000000,0.0
15,0000_pg,1,1.000000,0.0,0.000000,0.0,0.000000,46.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.0,1.000000,0.0
16,0000gokkai,1,0.000000,0.0,1.000000,0.0,1.000000,104.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.0,1.000000,0.0
17,0001000b,3,0.000000,0.0,0.333333,0.0,0.333333,76.666667,0.000000,0.000000,0.000000,0.000000,0.0,1.0,1.000000,0.0
18,0001Dilu,5,7.600000,0.0,3.600000,0.0,0.400000,179.800000,1.000000,0.600000,2.000000,0.000000,0.0,1.0,1.000000,0.0
19,0001Julio,1,0.000000,0.0,1.000000,0.0,0.000000,107.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.0,1.000000,0.0

In [ ]:
del user_meta
del df_raw
gc.collect()

28

In [ ]:
def preprocess_bitcoin_tweet(text):
    if pd.isna(text):
        return ""

    # mentions
    text = re.sub(r"@\w+", "@USER", text)

    # urls → nur Domain
    def repl(match):
        url = match.group(0)
        """try:
            domain = urlparse(url).netloc
            if domain:
                return f"HTTPURL_{domain}"
            else:
                return "HTTPURL"
        except:"""
        return "HTTPURL"
    text = re.sub(r"http\S+|www.\S+", repl, text)

    # hashtags
    #text = re.sub(r"#(\w+)", lambda m: f"HASHTAG_{m.group(1).lower()}", text)

    #CASHTAG
    text = re.sub(r"\$[A-Za-z]{1,10}", "CASHTAG", text)

    # multiple spaces → single
    text = " ".join(text.split())

    # lowercase
    #text = text.lower()

    return text

In [ ]:
chunks = []

for chunk in pd.read_csv("bitcoin_tweets.csv", chunksize=100_000):
    chunk["text"] = chunk["text"].map(preprocess_bitcoin_tweet)
    chunks.append(chunk)

df_raw = pd.concat(chunks, ignore_index=True)

In [ ]:
for i, text in enumerate(df_raw["text"]):
  if emoji.emoji_count(text) > 0:
    print(i, df_raw["text"].iloc[i])
    break

4 This is not freedom. Bitcoin vision crumbling by big banks and blockstream. BCH for the win. 💚 HTTPURL

In [ ]:
def preprocess_emojis(text):
    if not isinstance(text, str):
        return ""
    if emoji.emoji_count(text) == 0:
        return text
    # Emojis in Text umwandeln
    text = emoji.demojize(text)#, delimiters=(" ", " "))
    #text = emoji.demojize(text, language='en')
    # Optional: Platzhalter
    #text = re.sub(r":([a-z0-9_]+):", r"EMOJI_\1", text)
    return text

In [ ]:
print(preprocess_emojis("🐋🔥😡📜"))

:whale::fire::pouting_face::scroll:

In [ ]:
df_raw["text"] = df_raw["text"].apply(preprocess_emojis)

In [ ]:
for y, text in enumerate(df_raw["text"]):
  if emoji.emoji_count(text) > 0:
    print(y, df_raw.iloc[y])
    break

In [ ]:
print(df_raw["text"].iloc[i])

This is not freedom. Bitcoin vision crumbling by big banks and blockstream. BCH for the win. :green_heart: HTTPURL

In [ ]:
df_raw["datetime"]= pd.to_datetime(df_raw['datetime'])
df_raw= df_raw.sort_values(by="datetime")

In [ ]:
df_raw.head(100)

,Unnamed: 0,datetime,username,text
808037,6265269,2021-05-19 00:00:00+00:00,BitcoinLifeClub,NoCoiner? A person who doesn't own any #crypto...
9146250,6265270,2021-05-19 00:00:00+00:00,valueofcrypto,#Bitcoin Current Price: $ 42878.74 € 35112.95 ...
760811,6265267,2021-05-19 00:00:01+00:00,BitcoinBellyB,"The price of Spaghetti alla Carbonara is 25,62..."
3683724,6265268,2021-05-19 00:00:01+00:00,NikolaBench,:red_heart_selector:SHAKITA INU !!!! :dog_face...
757865,6265266,2021-05-19 00:00:02+00:00,BitcoinAverage,BitcoinAverage - bitcoin price index - ($ 4294...
...,...,...,...,...
2020616,6265178,2021-05-19 00:01:22+00:00,ECRIndy,Day 1 of #Indy500 practice complete! @USER use...
5067538,6265174,2021-05-19 00:01:25+00:00,WhaleTrades,":chart_decreasing::euro_banknote:$1,982,836 CA..."
3246480,6265173,2021-05-19 00:01:26+00:00,MadnessVs,"@USER &gt;Sell ""Bit coin is good."" &gt;Buy ""Bi..."
6117985,6265171,2021-05-19 00:01:29+00:00,bsv_is_bitcoin,"Mastercard funds BTC ""development"" literally. ..."
5537987,6265172,2021-05-19 00:01:29+00:00,beartrap221,@USER Elon Shooting at Bitcoin... HTTPURL

In [ ]:
df_raw.to_csv("bitcoin_tweets_clean.csv")

In [ ]:
del df_raw
del chunks

gc.collect()

0